# Generated by Django 3.1.8 on 2021-05-03 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20210425_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='case',
            name='confirm_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='case',
            name='events',
            field=models.ManyToManyField(blank=True, through='covid.Attendance', to='covid.Event'),
        ),
        migrations.AlterField(
            model_name='case',
            name='onset_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='cases',
            field=models.ManyToManyField(blank=True, through='covid.Attendance', to='covid.Case'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
